name: talks
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp>=0.11.1
  - asn1crypto
  - attrs
  - bokeh>=1.3.1
  - bzip2
  - cairo>=1.14.12
  - cartopy>=0.17.0
  - cffi>=1.12.3
  - cftime
  - chardet
  - cloudpickle
  - cryptography
  - curl
  - cycler
  - dask>=2.2.0
  - dask-core>=2.2.0
  - datashader>=0.7.0
  - datashape
  - dbus
  - descartes>=1.1.0
  - distributed>=2.2.0
  - expat
  - fiona>=1.8.4
  - fontconfig
  - freetype
  - freexl
  - fsspec
  - gdal
  - geopandas>=0.4.1
  - geos
  - geoviews>=1.6.2
  - geoviews-core>=1.6.2
  - gflags
  - giflib
  - glib
  - glog
  - gmp
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - heapdict
  - holoviews>=1.12.3
  - icu
  - idna
  - imageio
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - joblib
  - jpeg
  - json-c
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kealib
  - kiwisolver
  - krb5
  - libboost
  - libcurl
  - libdap4
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libkml
  - libnetcdf
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - mapclassify
  - markdown
  - markupsafe
  - matplotlib
  - mistune
  - mkl>=2019.4
  - mkl-service>=2.0.2
  - mkl_fft
  - mkl_random
  - multipledispatch
  - munch
  - nbconvert
  - nbformat
  - ncurses
  - netcdf4
  - networkx>=2.3
  - nodejs
  - notebook
  - numba>=0.45.0
  - numpy>=1.16.4
  - numpy-base>=1.16.4
  - olefile
  - openjpeg
  - openssl
  - owslib
  - packaging
  - pandas>=0.25.0
  - pandoc
  - pandocfilters
  - panel>=0.6.0
  - parso
  - partd
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip>=19.1.1
  - pixman
  - poppler
  - poppler-data
  - proj4
  - prometheus_client
  - prompt_toolkit>=2.0.9
  - psutil
  - psycopg2
  - ptyprocess
  - pyarrow>=0.11.1
  - pycparser=2.19
  - pyct
  - pyepsg
  - pygments
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pyshp
  - pysocks
  - python=3.7
  - python-dateutil
  - pytz
  - pyviz_comms
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests>=2.22.0
  - rise>=5.5.1
  - rtree
  - scikit-image
  - scikit-learn>=0.21.2
  - scipy>=1.3.0
  - seaborn>=0.9.0
  - send2trash
  - setuptools
  - shapely>=1.6.4
  - snappy
  - sortedcontainers>=2.1.0
  - sqlalchemy
  - sqlite
  - statsmodels>=0.10.1
  - tblib
  - terminado
  - testpath
  - thrift-cpp
  - tk
  - tornado>=6.0.3
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xarray
  - xerces-c
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - zstd

