name: bo
channels:
  - gpytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - botorch
  - cycler
  - cython
  - gpytorch
  - holoviews
  - ipython
  - joblib
  - jupyter
  - matplotlib
  - mkl
  - nodejs
  - notebook
  - numba
  - numpy
  - pip
  - plotly
  - pymc3
  - python=3.7.4
  - pytorch
  - requests
  - rise
  - scikit-learn
  - scipy
  - theano
  - xarray
  - pip:
    - ax-platform==0.1.6
